-- V6 finance wave: payments + expenses.
-- Mirrors Django payments/expenses apps; static expense categories seeded here.

CREATE TABLE PAYMENTS_PAYMENT (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  venture_id NUMBER(19) NOT NULL REFERENCES VENTURES_VENTURE(id) ON DELETE CASCADE,
  payment_type VARCHAR2(20) NOT NULL,
  reference_type VARCHAR2(20) NOT NULL,
  reference_id NUMBER(19) NOT NULL,
  amount NUMBER(14,2) NOT NULL,
  payment_date DATE NOT NULL,
  payment_method VARCHAR2(20) NOT NULL,
  transaction_reference VARCHAR2(100),
  notes VARCHAR2(255),
  created_by NUMBER(19) REFERENCES ACCOUNTS_USER(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_payment_type CHECK (payment_type IN ('RECEIVED','PAID')),
  CONSTRAINT chk_payment_reference CHECK (reference_type IN ('SALE','PURCHASE')),
  CONSTRAINT chk_payment_method CHECK (payment_method IN ('CASH','UPI','BANK_TRANSFER','CARD','OTHER'))
);
CREATE INDEX idx_payment_venture ON PAYMENTS_PAYMENT (venture_id);

CREATE TABLE EXPENSES_CATEGORY (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  category_code VARCHAR2(30) NOT NULL UNIQUE,
  category_name VARCHAR2(100) NOT NULL
);

CREATE TABLE EXPENSES_EXPENSE (
  id NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  venture_id NUMBER(19) NOT NULL REFERENCES VENTURES_VENTURE(id) ON DELETE CASCADE,
  category_id NUMBER(19) NOT NULL REFERENCES EXPENSES_CATEGORY(id),
  amount NUMBER(14,2) NOT NULL,
  expense_date DATE NOT NULL,
  payment_method VARCHAR2(20) NOT NULL,
  description VARCHAR2(255),
  created_by NUMBER(19) REFERENCES ACCOUNTS_USER(id) ON DELETE SET NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_expense_method CHECK (payment_method IN ('CASH','UPI','BANK_TRANSFER','CARD','OTHER'))
);
CREATE INDEX idx_expense_venture ON EXPENSES_EXPENSE (venture_id);

INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('ELECTRICITY', 'Electricity');
INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('TRANSPORT', 'Transport');
INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('RENT', 'Rent');
INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('SALARY', 'Salary');
INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('RAW_MATERIALS', 'Raw Materials');
INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('MARKETING', 'Marketing');
INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('MAINTENANCE', 'Maintenance');
INSERT INTO EXPENSES_CATEGORY (category_code, category_name) VALUES ('OTHER', 'Other');
