# Generated by Django 5.2.17 on 2026-09-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventures', '0002_venturecodecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('gst_number', models.CharField(blank=True, default='', max_length=20)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='ventures.venture')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
