# Generated by Django 5.2.17 on 2026-09-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('ventures', '0002_venturecodecounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('venture', 'customer_code'), name='uniq_customer_code_per_venture'),
        ),
    ]
