# Generated by Django 5.2.17 on 2026-09-23 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_seed_units'),
        ('ventures', '0002_venturecodecounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse_code', models.CharField(editable=False, max_length=20)),
                ('warehouse_name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('manager', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='ventures.venture')),
            ],
            options={
                'ordering': ['warehouse_name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('PURCHASE', 'Purchase receipt'), ('SALE', 'Sale dispatch'), ('PURCHASE_RETURN', 'Purchase return'), ('SALES_RETURN', 'Sales return'), ('ADJUSTMENT_IN', 'Adjustment in'), ('ADJUSTMENT_OUT', 'Adjustment out'), ('TRANSFER_IN', 'Transfer in'), ('TRANSFER_OUT', 'Transfer out')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('movement_date', models.DateField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('reference_type', models.CharField(blank=True, default='', max_length=40)),
                ('reference_id', models.CharField(blank=True, default='', max_length=40)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('paired_movement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='inventory.stockmovement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='ventures.venture')),
                ('destination_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.warehouse')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-movement_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reserved_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='products.product')),
                ('venture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='ventures.venture')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.warehouse')),
            ],
            options={
                'ordering': ['product__product_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('venture', 'warehouse_code'), name='uniq_warehouse_code_per_venture'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='uniq_inventory_wh_product'),
        ),
    ]
