-- ============================================================
-- V006__seed_platform.sql
-- Ajaya Venture root organization, initial business units,
-- baseline roles/permissions and the bootstrap admin user.
--
-- NOTE: the admin password for local/dev environments is the
-- bootstrap default "ChangeMe!2026" (stored as a PBKDF2-SHA256
-- hash). Rotate it before first use / in any non-local environment.
-- ============================================================

-- ---- Organization ---------------------------------------------------------
INSERT INTO AV_ORGANIZATION (
    ORGANIZATION_ID, ORGANIZATION_CODE, ORGANIZATION_NAME, LEGAL_NAME,
    DESCRIPTION, EMAIL, PHONE, WEBSITE, CITY, STATE_REGION, COUNTRY,
    DEFAULT_CURRENCY_CODE, DEFAULT_TIME_ZONE, STATUS, CREATED_BY
)
VALUES (1, 'AJV', 'Ajaya Venture', 'Ajaya Venture',
        'Parent business organization', 'info@ajayaventure.local', NULL, NULL,
        NULL, NULL, NULL, 'INR', 'Asia/Calcutta', 'ACTIVE', NULL);

-- ---- Business units ------------------------------------------------------
INSERT INTO AV_BUSINESS_UNIT (
    BUSINESS_UNIT_ID, ORGANIZATION_ID, BUSINESS_UNIT_CODE, BUSINESS_UNIT_NAME,
    BUSINESS_UNIT_TYPE, DESCRIPTION, STATUS, START_DATE, CREATED_BY
) VALUES (1, 1, 'ABMF', 'AB Mushroom Farming', 'MUSHROOM',
          'Mushroom cultivation and sales', 'ACTIVE', DATE '2026-01-01', NULL);

INSERT INTO AV_BUSINESS_UNIT (
    BUSINESS_UNIT_ID, ORGANIZATION_ID, BUSINESS_UNIT_CODE, BUSINESS_UNIT_NAME,
    BUSINESS_UNIT_TYPE, DESCRIPTION, STATUS, START_DATE, CREATED_BY
) VALUES (2, 1, 'AFF', 'Ajaya Fish Farming', 'FISH',
          'Fish stocking, feeding and harvest', 'ACTIVE', DATE '2026-01-01', NULL);

-- ---- Permissions ---------------------------------------------------------
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('ORG.VIEW',    'View organization',          'ORGANIZATION', 'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('ORG.MANAGE',  'Manage organization',        'ORGANIZATION', 'MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('BU.VIEW',     'View business units',        'BUSINESS_UNIT','VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('BU.MANAGE',   'Manage business units',      'BUSINESS_UNIT','MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('USER.VIEW',   'View users',                 'SECURITY',     'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('USER.MANAGE', 'Manage users and roles',     'SECURITY',     'MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('AUDIT.VIEW',  'View audit trail',           'SECURITY',     'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('MASTER.VIEW', 'View master data',           'MASTER_DATA',  'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('MASTER.MANAGE','Manage master data',        'MASTER_DATA',  'MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('FINANCE.VIEW','View finance data',          'FINANCE',      'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('FINANCE.MANAGE','Manage finance data',     'FINANCE',      'MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('INVENTORY.VIEW','View inventory',          'INVENTORY',    'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('INVENTORY.MANAGE','Manage inventory',       'INVENTORY',    'MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('PRODUCTION.VIEW','View production',         'PRODUCTION',   'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('PRODUCTION.MANAGE','Manage production',       'PRODUCTION',   'MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('SALES.VIEW',   'View sales',                'SALES',        'VIEW');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('SALES.MANAGE', 'Manage sales',              'SALES',        'MANAGE');
INSERT INTO AV_PERMISSION (PERMISSION_CODE, PERMISSION_NAME, MODULE_CODE, ACTION_CODE) VALUES ('REPORT.VIEW',  'View reports',              'REPORTS',      'VIEW');

-- ---- Roles ---------------------------------------------------------------
INSERT INTO AV_ROLE (ROLE_ID, ORGANIZATION_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, STATUS) VALUES (1, 1, 'OWNER',      'Owner',      'Full control of the organization', 'ACTIVE');
INSERT INTO AV_ROLE (ROLE_ID, ORGANIZATION_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, STATUS) VALUES (2, 1, 'ADMIN',      'Administrator','Administers users, masters and settings','ACTIVE');
INSERT INTO AV_ROLE (ROLE_ID, ORGANIZATION_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, STATUS) VALUES (3, 1, 'MANAGER',    'Manager',    'Runs operational modules',        'ACTIVE');
INSERT INTO AV_ROLE (ROLE_ID, ORGANIZATION_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, STATUS) VALUES (4, 1, 'STAFF',      'Staff',      'Records operational transactions', 'ACTIVE');
INSERT INTO AV_ROLE (ROLE_ID, ORGANIZATION_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, STATUS) VALUES (5, 1, 'ACCOUNTANT', 'Accountant', 'Finance, invoicing and payments',  'ACTIVE');
INSERT INTO AV_ROLE (ROLE_ID, ORGANIZATION_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, STATUS) VALUES (6, 1, 'VIEWER',     'Viewer',     'Read-only access',                'ACTIVE');

-- ---- Role > permission mappings ------------------------------------------
-- OWNER: everything
INSERT INTO AV_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT 1, PERMISSION_ID FROM AV_PERMISSION;
-- ADMIN: everything
INSERT INTO AV_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT 2, PERMISSION_ID FROM AV_PERMISSION;
-- MANAGER: operations + masters + reports (no ORG/USER management)
INSERT INTO AV_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT 3, PERMISSION_ID FROM AV_PERMISSION
WHERE PERMISSION_CODE IN ('BU.VIEW','MASTER.VIEW','MASTER.MANAGE','FINANCE.VIEW','FINANCE.MANAGE',
                          'INVENTORY.VIEW','INVENTORY.MANAGE','PRODUCTION.VIEW','PRODUCTION.MANAGE',
                          'SALES.VIEW','SALES.MANAGE','REPORT.VIEW','ORG.VIEW','AUDIT.VIEW');
-- STAFF: record transactions
INSERT INTO AV_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT 4, PERMISSION_ID FROM AV_PERMISSION
WHERE PERMISSION_CODE IN ('BU.VIEW','MASTER.VIEW','FINANCE.VIEW','INVENTORY.VIEW','INVENTORY.MANAGE',
                          'PRODUCTION.VIEW','PRODUCTION.MANAGE','SALES.VIEW','SALES.MANAGE');
-- ACCOUNTANT: finance + masters + reports
INSERT INTO AV_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT 5, PERMISSION_ID FROM AV_PERMISSION
WHERE PERMISSION_CODE IN ('BU.VIEW','MASTER.VIEW','FINANCE.VIEW','FINANCE.MANAGE','SALES.VIEW',
                          'REPORT.VIEW','ORG.VIEW','AUDIT.VIEW','INVENTORY.VIEW');
-- VIEWER: read-only
INSERT INTO AV_ROLE_PERMISSION (ROLE_ID, PERMISSION_ID)
SELECT 6, PERMISSION_ID FROM AV_PERMISSION
WHERE PERMISSION_CODE IN ('BU.VIEW','ORG.VIEW','MASTER.VIEW','FINANCE.VIEW','INVENTORY.VIEW',
                          'PRODUCTION.VIEW','SALES.VIEW','REPORT.VIEW');

-- ---- Bootstrap admin user -------------------------------------------------
INSERT INTO AV_USER (USER_ID, ORGANIZATION_ID, USERNAME, EMAIL, PASSWORD_HASH,
                     FIRST_NAME, LAST_NAME, STATUS, PASSWORD_CHANGED_AT)
VALUES (1, 1, 'admin', 'admin@ajayaventure.local',
        'pbkdf2-sha256$210000$Oci1whMtmFwog0S3PE0B0w==$wBdZ//Pj0jTQ+vb7I8JQiD0Y1hhd51AKa4v+xujueMM=',
        'Ajaya', 'Admin', 'ACTIVE', NULL);

INSERT INTO AV_USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);

-- Admin is assigned to both business units (full access)
INSERT INTO AV_USER_BUSINESS_UNIT (USER_ID, ORGANIZATION_ID, BUSINESS_UNIT_ID, ACCESS_LEVEL, STATUS, CREATED_BY)
VALUES (1, 1, 1, 'FULL', 'ACTIVE', 1);
INSERT INTO AV_USER_BUSINESS_UNIT (USER_ID, ORGANIZATION_ID, BUSINESS_UNIT_ID, ACCESS_LEVEL, STATUS, CREATED_BY)
VALUES (1, 1, 2, 'FULL', 'ACTIVE', 1);

COMMIT;