# Generated by Django 5.2.17 on 2026-09-23 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venture_code', models.CharField(editable=False, max_length=20, unique=True)),
                ('venture_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('business_type', models.CharField(choices=[('MUSHROOM', 'Mushroom'), ('FISH_FARMING', 'Fish Farming'), ('AGRICULTURE', 'Agriculture'), ('POULTRY', 'Poultry'), ('DAIRY', 'Dairy'), ('GENERAL', 'General'), ('OTHER', 'Other')], default='GENERAL', max_length=30)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('pincode', models.CharField(blank=True, default='', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], db_index=True, default='ACTIVE', max_length=10)),
            ],
            options={
                'verbose_name': 'Venture',
                'verbose_name_plural': 'Ventures',
                'ordering': ['venture_code'],
            },
        ),
    ]
