# Generated by Django 5.2.17 on 2026-09-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentureCodeCounter',
            fields=[
                ('id', models.PositiveIntegerField(default=1, primary_key=True, serialize=False)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Venture Code Counter',
                'verbose_name_plural': 'Venture Code Counters',
            },
        ),
    ]
