#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# AJAYA VENTURE - one-time database bootstrap.
# Creates the AV_MIGRATION / AV_APP / AV_REPORT schemas inside the configured
# pluggable database and installs the schema-migration tracking table.
#
# Usage:  bash scripts/bootstrap_db.sh
# Requires: running Oracle, admin credentials (defaults from .env or env vars).
# ---------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

if [[ -f "${ROOT_DIR}/.env" ]]; then
  set -a
  # shellcheck source=/dev/null
  source "${ROOT_DIR}/.env"
  set +a
fi

HOST="${DB_HOST:-localhost}"
PORT="${DB_PORT:-1521}"
SERVICE="${DB_SERVICE:-orclpdb}"
ADMIN_USER="${DB_APP_ADMIN_USERNAME:-sys}"
ADMIN_PASS="${DB_APP_ADMIN_PASSWORD:-oracle}"
ADMIN_ROLE="${DB_APP_ADMIN_ROLE:-sysdba}"

MIG_USER="${DB_MIGRATION_USERNAME:-AV_MIGRATION}"
MIG_PASS="${DB_MIGRATION_PASSWORD:-change-me}"
APP_USER="${DB_USERNAME:-AV_APP}"
APP_PASS="${DB_PASSWORD:-change-me}"
REP_USER="${AV_REPORT_USERNAME:-AV_REPORT}"
REP_PASS="${AV_REPORT_PASSWORD:-change-me}"

SQLPLUS="${SQLPLUS_BIN:-sqlplus}"
CONN_STRING="${ADMIN_USER}/${ADMIN_PASS}@//${HOST}:${PORT}/${SERVICE} as ${ADMIN_ROLE}"

echo "=== Bootstrap: connecting as ${ADMIN_USER} (${ADMIN_ROLE}) to ${SERVICE} ==="

"${SQLPLUS}" -L -S "${CONN_STRING}" <<SQL
SET ECHO OFF
SET FEEDBACK OFF
SET SERVEROUTPUT ON

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER AV_MIGRATION IDENTIFIED BY "${MIG_PASS}" QUOTA UNLIMITED ON USERS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -01920 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER AV_APP IDENTIFIED BY "${APP_PASS}"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -01920 THEN RAISE; END IF;
END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER AV_REPORT IDENTIFIED BY "${REP_PASS}"';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -01920 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER USER AV_MIGRATION QUOTA UNLIMITED ON USERS';
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO AV_MIGRATION';
  EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO AV_MIGRATION';
  EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO AV_MIGRATION';
  EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO AV_MIGRATION';
  EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO AV_MIGRATION';
  EXECUTE IMMEDIATE 'GRANT CREATE SYNONYM TO AV_MIGRATION';

  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO AV_APP';
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO AV_REPORT';
END;
/

-- Schema migration tracking table (owned by AV_MIGRATION)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE AV_MIGRATION.AV_SCHEMA_MIGRATION';
EXCEPTION WHEN OTHERS THEN IF SQLCODE <> -00942 THEN RAISE; END IF;
END;
/
CREATE TABLE AV_MIGRATION.AV_SCHEMA_MIGRATION (
  VERSION      VARCHAR2(40)  NOT NULL,
  FILENAME     VARCHAR2(255) NOT NULL,
  APPLIED_AT   TIMESTAMP(6)  DEFAULT SYSTIMESTAMP NOT NULL,
  APPLIED_BY   VARCHAR2(64),
  SUCCESS      VARCHAR2(1)   NOT NULL,
  CONSTRAINT PK_AV_SCHEMA_MIGRATION PRIMARY KEY (VERSION)
);
/
GRANT SELECT ON AV_MIGRATION.AV_SCHEMA_MIGRATION TO AV_APP;
GRANT SELECT ON AV_MIGRATION.AV_SCHEMA_MIGRATION TO AV_REPORT;
PROMPT Bootstrap complete.
SQL

echo "=== Done. Run: bash scripts/migrate.sh ==="