# Generated by Django 5.2.17 on 2026-09-23 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventures', '0002_venturecodecounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=40)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('venture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ventures.venture')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('module', 'venture'), name='uniq_sequence_module_venture')],
            },
        ),
    ]
